name: Build Android App (Unsigned)

on:
  workflow_dispatch: # Ejecutar manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Dar permisos de ejecución
        run: chmod +x ./gradlew

      - name: Compilar AAB sin firma
        run: ./gradlew bundleRelease

      - name: Guardar archivo .aab como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: app/build/outputs/bundle/release/app-release.aab

      
